// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using loginAuth.Data;

#nullable disable

namespace loginAuth.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20240719020529_updatedentity1")]
    partial class updatedentity1
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("loginAuth.Models.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Admin"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Manager"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Employee"
                        });
                });

            modelBuilder.Entity("loginAuth.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "admin1@gmail.com",
                            FirstName = "john",
                            LastName = "Mary",
                            Password = "admin1",
                            RoleId = 1
                        },
                        new
                        {
                            Id = 2,
                            Email = "admin2@gmail.com",
                            FirstName = "jim",
                            LastName = "Mary",
                            Password = "admin2",
                            RoleId = 1
                        },
                        new
                        {
                            Id = 3,
                            Email = "manager1@gmail.com",
                            FirstName = "john",
                            LastName = "josephy",
                            Password = "manager1",
                            RoleId = 2
                        },
                        new
                        {
                            Id = 4,
                            Email = "manager2@gmail.com",
                            FirstName = "jin",
                            LastName = "tom",
                            Password = "manager2",
                            RoleId = 2
                        },
                        new
                        {
                            Id = 5,
                            Email = "employee1@gmail.com",
                            FirstName = "tim",
                            LastName = "Mary",
                            Password = "employee1",
                            RoleId = 3
                        },
                        new
                        {
                            Id = 6,
                            Email = "employee2@gmail.com",
                            FirstName = "josh",
                            LastName = "Mary",
                            Password = "employee2",
                            RoleId = 3
                        });
                });

            modelBuilder.Entity("loginAuth.Models.User", b =>
                {
                    b.HasOne("loginAuth.Models.Role", "Role")
                        .WithMany("Users")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");
                });

            modelBuilder.Entity("loginAuth.Models.Role", b =>
                {
                    b.Navigation("Users");
                });
#pragma warning restore 612, 618
        }
    }
}
